library(usethis)

Regulon_Activity_Matrix_TILs = readRDS(file="./Regulon_Activity_Matrix_TILs.Toy.Rds")
Gene_Expression_Matrix_TILs = readRDS(file="./Gene_Expression_Matrix_TILs.Toy.Rds")
Annotation_TILs = readRDS(file="./Annotation_TILs.Toy.Rds")
Regulons_TILs = readRDS(file="./Regulons.from.network.TILS.wo.Tox.Rds")
Tox_Regulons_TILs = readRDS(file="./Tox.regulon.Rds")
Modulons_TILs = readRDS(file="./TF.AUC.clusters.TILs.Rds")

usethis::use_data(Regulon_Activity_Matrix_TILs, overwrite = TRUE)
usethis::use_data(Gene_Expression_Matrix_TILs, overwrite = TRUE)
usethis::use_data(Annotation_TILs, overwrite = TRUE)
usethis::use_data(Regulons_TILs, overwrite = TRUE)
usethis::use_data(Modulons_TILs, overwrite = TRUE)
usethis::use_data(Tox_Regulons_TILs, overwrite = TRUE)